### ISSUE TITLE
SMS Cli appears to crash MME

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3546]
### Your Environment

- **Version:** v1.3 stable (patched MME and patched uplink_bridge.py)
- **Affected Component:** Orchestrator & Access Gateway
- **Affected Subcomponent:** SMSd and MME
- **Deployment Environment:** e.g. AWS (orc8r) , bare-metal (AGW), iPhone 11pro

### Describe the Issue

Trying to test SMS functionality via SMSd. 
I first used API to try to send SMS to IMSI, but it returns 0 attempts and status waiting. (see screenshot)

I then tried to use the sms_cli to send the SMS, but that appears to crash the mme. 

**To Reproduce**
1. Attach iPhone 11pro to Network
2. Via SSH in AGW, issue sms_cli du mesage to UE e.g.` sms_cli.py DU 315010999900110 1fc13a00`
3. Observe journal where MME sig terms and restarts

**Expected behavior**
Expected behavior is SMS is delivered to phone or fails without taking down mme. 

**Screenshots**
Screenshot of API SMS none-delivery

**Additional context**
ZIp of:
console log of command
pcap of s1
mme.log
journal of sequence of UE attach, issue sms_cli.py command,  mme sig term
[10:29 Testing.zip](https://github.com/magma/magma/files/5463050/10.29.Testing.zip)

Test Network drawing (orc8r in AWS)
![SMS iPhone Test](https://user-images.githubusercontent.com/61293007/97661478-0d63c600-1a3a-11eb-8fd4-537193bb0df6.png)

**Comment by ulaskozat** [comment]
@jpad-freedomfi SMS feature is intended for v1.3.1. Not sure how the patched MME would behave. I can send you what I have on master to patch mme again and retest. That should fix the behavior you observe on the Orc8r side (it will show the status correctly as delivered when delivered).

On the raised segfault, I think you did not change the mode of `non_eps_service_control` as it seems the service is not running. Note that sms CLI is intended for debugging. You can change `non_eps_service_control` via API end point `/lte/{network_id}/gateways/{gateway_id}/cellular/non_eps`. Below is a sample you can use as the needed config:
```
{
  "arfcn_2g": [
    0
  ],
  "csfb_mcc": "001",
  "csfb_mnc": "01",
  "csfb_rat": 0,
  "lac": 1,
  "non_eps_service_control": 3
}
```

**Comment by ulaskozat** [comment]
PR #3552 fixes the crash issue. When SMS service is not configured, GRPC service will be disabled and SMS delivery will fail without any crash. For enabling and testing the service you can follow the steps I posted.

For CLI, I suggest to use 
`sms_cli.py DU 315010999900110 090123010002b911001c2406912143650000020103911140000dc8329bfd06dddf7236591602`

which should be sending `Hello world2!`

**Comment by jpad-freedomfi** [comment]
Hi @ulaskozat and @joary 

I have tested per comments above. Here is my config:
`/lte/{network_id}/gateways/{gateway_id}/cellular/non_eps` 
which contains:
```
{
  "arfcn_2g": [
    0
  ],
  "csfb_mcc": "315",
  "csfb_mnc": "010",
  "csfb_rat": 0,
  "lac": 1,
  "non_eps_service_control": 3
}
```

We are running v1.3 branch at commit de7c8e314fc2388da17f327adae838a919fda2e9 

The CLI python tool works! (tested with OnePlus 7T UE, band 28 on Nokia cell, Android 10)

API triggered SMS does not seem to work. journalctl on AGW reports:
```
magma@agw:~$ sudo journalctl -fu magma@smsd
-- Logs begin at Tue 2020-11-24 11:08:56 PST. --
Nov 24 11:43:56 agw smsd[1288]: task: <Task pending coro=<Job._periodic() running at /usr/local/lib/python3.5/dist-packages/magma/common/job.py:129> wait_for=<Future pending cb=[Task._wakeup()]>>
Nov 24 11:43:56 agw smsd[1288]: sys:1: RuntimeWarning: coroutine 'Job._sleep_for_interval' was never awaited
Nov 24 11:43:56 agw smsd[1288]: ERROR:asyncio:Task was destroyed but it is pending!
Nov 24 11:43:56 agw smsd[1288]: task: <Task pending coro=<Job._sleep_for_interval() running at /usr/local/lib/python3.5/dist-packages/magma/common/job.py:100>>
Nov 24 11:43:56 agw systemd[1]: Stopped Magma smsd service.
Nov 24 11:43:56 agw systemd[1]: Started Magma smsd service.
Nov 24 11:43:57 agw smsd[15863]: WARNING:root:Service (smsd) missing in mconfig
Nov 24 11:43:57 agw smsd[15863]: INFO:root:Starting smsd...
Nov 24 11:43:57 agw smsd[15863]: INFO:root:Listening on address 127.0.0.1:50078
Nov 24 11:43:57 agw smsd[15863]: INFO:root:Checking SMS for 2 IMSIs
Nov 24 11:44:12 agw smsd[15863]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Nov 24 11:44:12 agw smsd[15863]:         status = StatusCode.DEADLINE_EXCEEDED
Nov 24 11:44:12 agw smsd[15863]:         details = "Deadline Exceeded"
Nov 24 11:44:12 agw smsd[15863]:         debug_error_string = "{"created":"@1606247052.079444274","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Nov 24 11:44:12 agw smsd[15863]: >
```

**Comment by jpad-freedomfi** [comment]
Hi @ulaskozat (and FYI @joary)

I have updated AGW and 0rc8r to 1.3.2 tag. I still see similar error when trying to use SMS via API. Here are SMSd logs seen while I have an SMS waiting in orc8r queue

my non-eps setting matches note above for this GW still. 

And, similar to above, sms.cli DOES work. 

Any ideas what is going on? 

```
magma@agw:~$ sudo systemctl restart magma@smsd
magma@agw:~$ sudo journalctl -fu magma@smsd
-- Logs begin at Fri 2020-12-04 03:13:56 PST. --
Dec 04 08:17:10 agw smsd[23326]:   File "/usr/lib/python3.5/asyncio/futures.py", line 285, in result
Dec 04 08:17:10 agw smsd[23326]:     raise CancelledError
Dec 04 08:17:10 agw smsd[23326]: concurrent.futures._base.CancelledError
Dec 04 08:17:10 agw smsd[23326]: ERROR:asyncio:Task was destroyed but it is pending!
Dec 04 08:17:10 agw smsd[23326]: task: <Task pending coro=<Job._periodic() running at /usr/local/lib/python3.5/dist-packages/magma/common/job.py:129> wait_for=<Future pending cb=[Task._wakeup()]>>
Dec 04 08:17:10 agw smsd[23326]: sys:1: RuntimeWarning: coroutine 'Job._sleep_for_interval' was never awaited
Dec 04 08:17:10 agw smsd[23326]: ERROR:asyncio:Task was destroyed but it is pending!
Dec 04 08:17:10 agw smsd[23326]: task: <Task pending coro=<Job._sleep_for_interval() running at /usr/local/lib/python3.5/dist-packages/magma/common/job.py:100>>
Dec 04 08:17:12 agw systemd[1]: Stopped Magma smsd service.
Dec 04 08:17:12 agw systemd[1]: Started Magma smsd service.
Dec 04 08:17:13 agw smsd[2255]: WARNING:root:Service (smsd) missing in mconfig
Dec 04 08:17:13 agw smsd[2255]: INFO:root:Starting smsd...
Dec 04 08:17:13 agw smsd[2255]: INFO:root:Listening on address 127.0.0.1:50078
Dec 04 08:17:13 agw smsd[2255]: INFO:root:Checking SMS for 2 IMSIs
Dec 04 08:17:28 agw smsd[2255]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Dec 04 08:17:28 agw smsd[2255]:         status = StatusCode.DEADLINE_EXCEEDED
Dec 04 08:17:28 agw smsd[2255]:         details = "Deadline Exceeded"
Dec 04 08:17:28 agw smsd[2255]:         debug_error_string = "{"created":"@1607098648.696657752","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 04 08:17:28 agw smsd[2255]: >
Dec 04 08:17:33 agw smsd[2255]: INFO:root:Checking SMS for 2 IMSIs
Dec 04 08:17:48 agw smsd[2255]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Dec 04 08:17:48 agw smsd[2255]:         status = StatusCode.DEADLINE_EXCEEDED
Dec 04 08:17:48 agw smsd[2255]:         details = "Deadline Exceeded"
Dec 04 08:17:48 agw smsd[2255]:         debug_error_string = "{"created":"@1607098668.714656439","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 04 08:17:48 agw smsd[2255]: >
Dec 04 08:17:53 agw smsd[2255]: INFO:root:Checking SMS for 2 IMSIs
Dec 04 08:18:08 agw smsd[2255]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Dec 04 08:18:08 agw smsd[2255]:         status = StatusCode.DEADLINE_EXCEEDED
Dec 04 08:18:08 agw smsd[2255]:         details = "Deadline Exceeded"
Dec 04 08:18:08 agw smsd[2255]:         debug_error_string = "{"created":"@1607098688.730647939","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 04 08:18:08 agw smsd[2255]: >
Dec 04 08:18:13 agw smsd[2255]: INFO:root:Checking SMS for 2 IMSIs
Dec 04 08:18:28 agw smsd[2255]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Dec 04 08:18:28 agw smsd[2255]:         status = StatusCode.DEADLINE_EXCEEDED
Dec 04 08:18:28 agw smsd[2255]:         details = "Deadline Exceeded"
Dec 04 08:18:28 agw smsd[2255]:         debug_error_string = "{"created":"@1607098708.746658602","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 04 08:18:28 agw smsd[2255]: >
Dec 04 08:18:33 agw smsd[2255]: INFO:root:Checking SMS for 2 IMSIs
Dec 04 08:18:48 agw smsd[2255]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Dec 04 08:18:48 agw smsd[2255]:         status = StatusCode.DEADLINE_EXCEEDED
Dec 04 08:18:48 agw smsd[2255]:         details = "Deadline Exceeded"
Dec 04 08:18:48 agw smsd[2255]:         debug_error_string = "{"created":"@1607098728.765657666","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 04 08:18:48 agw smsd[2255]: >
Dec 04 08:18:53 agw smsd[2255]: INFO:root:Checking SMS for 2 IMSIs
Dec 04 08:19:08 agw smsd[2255]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Dec 04 08:19:08 agw smsd[2255]:         status = StatusCode.DEADLINE_EXCEEDED
Dec 04 08:19:08 agw smsd[2255]:         details = "Deadline Exceeded"
Dec 04 08:19:08 agw smsd[2255]:         debug_error_string = "{"created":"@1607098748.783655887","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 04 08:19:08 agw smsd[2255]: >
Dec 04 08:19:13 agw smsd[2255]: INFO:root:Checking SMS for 2 IMSIs
```

**Comment by ulaskozat** [comment]
@jpad-freedomfi did not receive any notification on this, just seeing your notes. Have you configured `nonEpsServiceControl` to use value 3? If it is not set to 3, SMS service will not run on the MME process.

**Comment by jpad-freedomfi** [comment]
Hi @ulaskozat yes here is my non-eps config

```
{
  "arfcn_2g": [
    0
  ],
  "csfb_mcc": "315",
  "csfb_mnc": "010",
  "csfb_rat": 0,
  "lac": 1,
  "non_eps_service_control": 3
}
```

**Comment by ulaskozat** [comment]
@jpad-freedomfi this looks correct. From your logs, it looks like GRPC call is timing out. I will check if I can replicate the issue on my side..

**Comment by ulaskozat** [comment]
@jpad-freedomfi the failing GRPC call is from AGW to Orc8r, are we sure that the service is running on the orc8r side?

**Comment by ulaskozat** [comment]
or maybe a data migration is not performed on orc8r side?

**Comment by joary** [comment]
@jpad-freedomfi, can you share the orc8r-controller pod logs?

From a machine with kubernetes access, you will need to list the pods in orc8r with

`kubectl -norc8r get pods`

Grab the orc8r-controller pod name:

```
...
orc8r-controller-aaaaaaaaaaa-bbbbb                1/1     Running   0          6d18h
orc8r-controller-aaaaaaaaaaa-ccccc                1/1     Running   0          6d18h
...
```

Then execute this to grab the logs for each one.

`kubectl -norc8r logs orc8r-controller-aaaaaaaaaaa-bbbbb`

**Comment by joary** [comment]
@jpad-freedomfi, as @ulaskozat proposed, lets check if smsd is running in your controller, with:

`kubectl exec -norc8r orc8r-controller-aaaaaaaaaaa-bbbbb  bash -- supervisorctl status`

remenber to use the orc8r-controller name you got from `kubectl -norc8r get pods`

we expect to see something like:

```
...
smsd                             RUNNING   pid 22, uptime 6 days, 19:53:27
...
```

**Comment by ulaskozat** [comment]
@jpad-freedomfi can we close on this issue?

**Comment by jpad-freedomfi** [comment]
Hi @ulaskozat and @joary 

So far I haven't been able to get into our orc8r for lab or prod env where I can test SMS. I will work with @119Vik tomorrow to get in and check the status of smsd in orc8r. 

Is the smsd running by default on the orc8r side? We have used documentation here to upgrade/install 1.3.2 https://docs.magmacore.org/docs/orc8r/upgrade_1_3 

But I don't see specific mention of how to setup smsd (if any specific steps are needed) on the orc8r side.

**Comment by jpad-freedomfi** [comment]
@ulaskozat and @joary 

here is orc8r status
```
  lab_env git:(master) ✗ kubectl -n orc8r get pods
NAME                                             READY   STATUS    RESTARTS   AGE
fluentd-8549d4684f-bhjh6                         1/1     Running   0          56d
fluentd-8549d4684f-pprgv                         1/1     Running   0          56d
nms-magmalte-646ff556cf-8vn64                    1/1     Running   0          11d
nms-nginx-proxy-57b8585d6-vjgdn                  1/1     Running   0          27d
orc8r-alertmanager-84d79f774b-9f2fl              1/1     Running   0          56d
orc8r-alertmanager-configurer-68d6c55c9c-866pg   1/1     Running   0          56d
orc8r-controller-58ddfcff7b-79sbt                1/1     Running   0          11d
orc8r-controller-58ddfcff7b-nh5pv                1/1     Running   0          11d
orc8r-nginx-68f787bd8f-bql4z                     1/1     Running   0          11d
orc8r-nginx-68f787bd8f-sz8sm                     1/1     Running   0          11d
orc8r-prometheus-69665f5776-r2sbk                1/1     Running   0          56d
orc8r-prometheus-cache-9c859bfc6-bn2c5           1/1     Running   0          56d
orc8r-prometheus-configurer-698cfb7bc6-n9pkf     1/1     Running   0          56d
orc8r-user-grafana-bc644b4fc-4rlj7               1/1     Running   0          56d
➜  lab_env git:(master) ✗ kubectl exec -n orc8r orc8r-controller-58ddfcff7b-nh5pv bash -- supervisorctl status
accessd                          RUNNING   pid 23, uptime 11 days, 5:09:47
analytics                        FATAL     Exited too quickly (process log may have details)
bootstrapper                     RUNNING   pid 11, uptime 11 days, 5:09:47
certifier                        RUNNING   pid 26, uptime 11 days, 5:09:47
configurator                     RUNNING   pid 38, uptime 11 days, 5:09:47
cwf                              FATAL     Exited too quickly (process log may have details)
dev_setup                        EXITED    Dec 04 10:54 AM
device                           RUNNING   pid 27, uptime 11 days, 5:09:47
directoryd                       RUNNING   pid 36, uptime 11 days, 5:09:47
dispatcher                       RUNNING   pid 28, uptime 11 days, 5:09:47
download                         FATAL     Exited too quickly (process log may have details)
fbinternal                       FATAL     Exited too quickly (process log may have details)
feg                              RUNNING   pid 25, uptime 11 days, 5:09:47
feg_relay                        RUNNING   pid 10, uptime 11 days, 5:09:47
health                           RUNNING   pid 21, uptime 11 days, 5:09:47
lte                              RUNNING   pid 33, uptime 11 days, 5:09:47
metricsd                         RUNNING   pid 17, uptime 11 days, 5:09:47
obsidian                         RUNNING   pid 34, uptime 11 days, 5:09:47
orchestrator                     RUNNING   pid 24, uptime 11 days, 5:09:47
policydb                         RUNNING   pid 31, uptime 11 days, 5:09:47
service_registry                 RUNNING   pid 16, uptime 11 days, 5:09:47
smsd                             RUNNING   pid 18, uptime 11 days, 5:09:47
state                            RUNNING   pid 20, uptime 11 days, 5:09:47
stdout                           RUNNING   pid 8, uptime 11 days, 5:09:47
streamer                         RUNNING   pid 14, uptime 11 days, 5:09:47
subscriberdb                     RUNNING   pid 19, uptime 11 days, 5:09:47
tenants                          RUNNING   pid 35, uptime 11 days, 5:09:47
testcontroller                   FATAL     Exited too quickly (process log may have details)
vpnservice                       FATAL     Exited too quickly (process log may have details)
wifi                             FATAL     Exited too quickly (process log may have details)
```

**Comment by jpad-freedomfi** [comment]
smsd uptime is 11d looks like

**Comment by jpad-freedomfi** [comment]
Logs from orc8r (nothing mentioning sms or smsd)
[orc8r_logs.txt](https://github.com/magma/magma/files/5697163/orc8r_logs.txt)

**Comment by joary** [comment]
Hi Joey, can you share the open ports in this AGW, with: `netstat -tunlp`.

Also can you share an updated mme.log? to check if the SMS_ORC8R task active in MME.

**Comment by jpad-freedomfi** [comment]
Hi @joary and @ulaskozat Happy holidays! Here are the requested logs from above. Best I can tell the port is open (python process PID 1364) and the SMS_ORC8R task does appear active. 

[listening_port_and_mme_log.txt](https://github.com/magma/magma/files/5743975/listening_port_and_mme_log.txt)

**Comment by jpad-freedomfi** [comment]
as a recent update, here is the smsd output:
```
magma@agw:~$ sudo journalctl -fu magma@smsd
-- Logs begin at Sat 2020-12-26 17:04:50 PST. --
Dec 26 17:46:23 agw smsd[1364]:         details = "Deadline Exceeded"
Dec 26 17:46:23 agw smsd[1364]:         debug_error_string = "{"created":"@1609033583.784927396","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 26 17:46:23 agw smsd[1364]: >
Dec 26 17:46:28 agw smsd[1364]: INFO:root:Checking SMS for 1 IMSIs
Dec 26 17:46:43 agw smsd[1364]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Dec 26 17:46:43 agw smsd[1364]:         status = StatusCode.DEADLINE_EXCEEDED
Dec 26 17:46:43 agw smsd[1364]:         details = "Deadline Exceeded"
Dec 26 17:46:43 agw smsd[1364]:         debug_error_string = "{"created":"@1609033603.793016705","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 26 17:46:43 agw smsd[1364]: >
Dec 26 17:46:48 agw smsd[1364]: INFO:root:Checking SMS for 1 IMSIs
Dec 26 17:47:03 agw smsd[1364]: ERROR:root:GRPC call failed while fetching messages: <_Rendezvous of RPC that terminated with:
Dec 26 17:47:03 agw smsd[1364]:         status = StatusCode.DEADLINE_EXCEEDED
Dec 26 17:47:03 agw smsd[1364]:         details = "Deadline Exceeded"
Dec 26 17:47:03 agw smsd[1364]:         debug_error_string = "{"created":"@1609033623.800967911","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Deadline Exceeded","grpc_status":4}"
Dec 26 17:47:03 agw smsd[1364]: >
Dec 26 17:47:08 agw smsd[1364]: INFO:root:Checking SMS for 1 IMSIs
^C
magma@agw:~$ 
```

**Comment by sourabh-nanoti** [comment]
Hi @jpad-freedomfi  I wanted to check  some things  on your orc8r if possible 

1. Can you try to set and get SMS using API docs to see if can get the SMSs successfully? 
<img width="1307" alt="Screen Shot 2021-01-13 at 11 47 32 AM" src="https://user-images.githubusercontent.com/48265190/104404240-2d187e00-5595-11eb-8cc5-e2ba67d97655.png">

2. Can you check if you we have logs of the AGW GRPC reaching Orc8r using API ? 
<img width="1301" alt="Screen Shot 2021-01-13 at 11 44 35 AM" src="https://user-images.githubusercontent.com/48265190/104404298-4d483d00-5595-11eb-92f2-9b8373864f67.png">
Here you should see logs like below every 5 sec approx 
 {
    "_index": "magma-2021.01.12",
    "_type": "_doc",
    "_id": "7MB99nYBbjrn82aypM2f",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1610435190000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan 12 07:06:30",
      "host": "magma",
      "ident": "control_proxy",
      "pid": "788",
      "message": "2021-01-12T07:06:30.653-05:00 [127.0.0.1 -> smsd-controller.baicells.magmatest.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 200 5bytes 0.805s",
      "hw_id": "3259ec07-d1a1-4ca3-a3c2-10e274c9f11d",
      "network_id": "magma_baicellsmyanmar",
      "gateway_id": "agw_dellvisto",
      "@timestamp": "2021-01-12T07:06:30.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },

**Comment by jpad-freedomfi** [comment]
logs search appeared to be a hit. I am getting 503 response. 

```
[
  {
    "_index": "magma-2021.01.11",
    "_type": "_doc",
    "_id": "kUgW83YBIOEwWqrWplBE",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1610367304000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan 11 12:15:04",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "10992",
      "message": "2021-01-11T12:15:04.014-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 0.000s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "network_id": "test_federated_lte",
      "gateway_id": "nuc",
      "@timestamp": "2021-01-11T12:15:04.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.11",
    "_type": "_doc",
    "_id": "_2oV83YBievYqBFm_1eJ",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1610367259000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan 11 12:14:19",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "10992",
      "message": "2021-01-11T12:14:19.607-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 0.000s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "network_id": "test_federated_lte",
      "gateway_id": "nuc",
      "@timestamp": "2021-01-11T12:14:19.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.11",
    "_type": "_doc",
    "_id": "NWoV83YBievYqBFm_1eJ",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1610367254000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan 11 12:14:14",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "10992",
      "message": "2021-01-11T12:14:14.523-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 0.000s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "network_id": "test_federated_lte",
      "gateway_id": "nuc",
      "@timestamp": "2021-01-11T12:14:14.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.11",
    "_type": "_doc",
    "_id": "MmoV83YBievYqBFm_1aJ",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1610367249000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan 11 12:14:09",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "10992",
      "message": "2021-01-11T12:14:09.101-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 0.000s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "network_id": "test_federated_lte",
      "gateway_id": "nuc",
      "@timestamp": "2021-01-11T12:14:09.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.11",
    "_type": "_doc",
    "_id": "rWoW83YBievYqBFmFF2E",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1610367244000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan 11 12:14:04",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "10992",
      "message": "2021-01-11T12:14:04.358-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 0.000s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "network_id": "test_federated_lte",
      "gateway_id": "nuc",
      "@timestamp": "2021-01-11T12:14:04.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.11",
    "_type": "_doc",
    "_id": "TmoW83YBievYqBFmFFyE",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1610367214000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan 11 12:13:34",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "10992",
      "message": "2021-01-11T12:13:34.782-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 14.990s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "network_id": "test_federated_lte",
      "gateway_id": "nuc",
      "@timestamp": "2021-01-11T12:13:34.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.05",
    "_type": "_doc",
    "_id": "MB6U1XYBievYqBFmX-VQ",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1609872228000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan  5 18:43:48",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "29299",
      "message": "2021-01-05T18:43:48.136-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 0.000s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "gateway_id": "nuc",
      "network_id": "test_federated_lte",
      "@timestamp": "2021-01-05T18:43:48.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.05",
    "_type": "_doc",
    "_id": "FvyU1XYBIOEwWqrWO-Hr",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1609872223000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan  5 18:43:43",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "29299",
      "message": "2021-01-05T18:43:43.125-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 0.000s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "gateway_id": "nuc",
      "network_id": "test_federated_lte",
      "@timestamp": "2021-01-05T18:43:43.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.05",
    "_type": "_doc",
    "_id": "tPyT1XYBIOEwWqrW9N8M",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1609872193000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan  5 18:43:13",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "29299",
      "message": "2021-01-05T18:43:13.078-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 0.425s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "gateway_id": "nuc",
      "network_id": "test_federated_lte",
      "@timestamp": "2021-01-05T18:43:13.000000000+00:00",
      "tag": "gateway.syslog"
    }
  },
  {
    "_index": "magma-2021.01.05",
    "_type": "_doc",
    "_id": "zPyT1XYBIOEwWqrW9NwL",
    "_seq_no": null,
    "_primary_term": null,
    "sort": [
      1609872167000
    ],
    "_source": {
      "pri": "30",
      "time": "Jan  5 18:42:47",
      "host": "agw",
      "ident": "control_proxy",
      "pid": "29299",
      "message": "2021-01-05T18:42:47.631-08:00 [127.0.0.1 -> smsd-controller.lab.freedomfi.com,8443] \"POST /magma.lte.SmsD/GetMessages HTTP/2\" 503 160bytes 4.988s",
      "hw_id": "7bf97027-6442-4641-9736-4caf544f4ed7",
      "gateway_id": "nuc",
      "network_id": "test_federated_lte",
      "@timestamp": "2021-01-05T18:42:47.000000000+00:00",
      "tag": "gateway.syslog"
    }
  }
]
```

**Comment by jpad-freedomfi** [comment]
I have a message waiting in the queue for same network

```
[
  {
    "attempt_count": 0,
    "imsi": "IMSI315010999900109",
    "message": "Hello world!",
    "pk": "eb873906-18c5-4319-8d1c-e08213a08231",
    "source_msisdn": "123456",
    "status": "Waiting",
    "time_created": "2020-11-24T19:06:17.000Z",
    "time_last_attempted": "0001-01-01T00:00:00.000Z"
  }
]
```

**Comment by sourabh-nanoti** [comment]
Ok. This seems odd. At my end i see 200. May be i should investigate here then. 
<img width="1127" alt="Screen Shot 2021-01-13 at 12 00 18 PM" src="https://user-images.githubusercontent.com/48265190/104405024-fc394880-5596-11eb-948d-ada1be8b2f39.png">

**Comment by jpad-freedomfi** [comment]
agree, 503 is a bad sign. I have sent you WhatsApp message to. We can connect there for more realtime.

**Comment by ulaskozat** [comment]
Folks I cannot replicate this issue on my set up.

**Comment by sourabh-nanoti** [comment]
Can we just compare the o/p of the following command in the orc8r-controller pod as well at your orc8r? @119Vik @jpad-freedomfi 

root@ip-172-31-11-83:~/terraform-magma# kubectl exec -it  orc8r-controller-854c864d7b-5wshf  bash 
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@orc8r-controller-854c864d7b-5wshf:/# ps -eaf | grep smsd
root        22     1  0 Jan06 ?        00:01:18 /var/opt/magma/bin/smsd -run_echo_server=true -logtostderr=true -v=0
root       523   512  0 05:44 pts/0    00:00:00 grep --color=auto smsd
root@orc8r-controller-854c864d7b-5wshf:/# netstat -nap | grep smsd
tcp        0      0 127.0.0.1:51414         127.0.0.1:9108          ESTABLISHED 22/smsd         
tcp        0      0 127.0.0.1:35806         127.0.0.1:9086          ESTABLISHED 22/smsd         
tcp        0      0 10.10.100.201:41994     10.10.201.175:5432      ESTABLISHED 22/smsd         
tcp6       0      0 :::10086                :::*                    LISTEN      22/smsd         
tcp6       0      0 :::9120                 :::*                    LISTEN      22/smsd         
tcp6       0      0 127.0.0.1:9120          127.0.0.1:51898         ESTABLISHED 22/smsd         
root@orc8r-controller-854c864d7b-5wshf:/# netstat

**Comment by jpad-freedomfi** [comment]
Here ya go:
```
root@orc8r-controller-58ddfcff7b-79sbt:/# ps -eaf | grep smsd
root        23     1  0  2020 ?        00:01:50 /var/opt/magma/bin/smsd -run_echo_server=true -logtostderr=true -v=0
root      1864  1853  0 12:57 pts/0    00:00:00 grep --color=auto smsd
root@orc8r-controller-58ddfcff7b-79sbt:/bin# netstat -nap | grep smsd
tcp        0      0 10.10.100.134:50906     10.10.201.219:5432      ESTABLISHED 23/smsd         
tcp6       0      0 :::10086                :::*                    LISTEN      23/smsd         
tcp6       0      0 :::9120                 :::*                    LISTEN      23/smsd    
```

**Comment by jpad-freedomfi** [comment]
my netstat has 2 less established lines than yours.
oh, and no IPv6 established connections

**Comment by jpad-freedomfi** [comment]
On the controller pod, here is my /etc/magma/configs/lte/service_registry.yml
```
  smsd:
    host: "localhost"
    port: 9120
    echo_port: 10086
    proxy_type: "clientcert"
    labels:
      orc8r.io/obsidian_handlers: "true"
    annotations:
      orc8r.io/obsidian_handlers_path_prefixes: >
        /magma/v1/lte/:network_id/sms,
```

here is /etc/magma/configs/orc8r/service_registry.yml 
```
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# proxy_type refers to the names of the proxy systemd nghttpx services installed.
# Currently the values supported are: 'clientcert', 'open', 'obsidian', 'internal'

# proxy_aliases refers to proxy config when a service might have more than one
# port. Example in magma/feg/cloud/configs/service_registry.yml

services:
  orchestrator:
    host: "localhost"
    port: 9112
    echo_port: 10112
    proxy_type: "clientcert"
    labels:
      orc8r.io/mconfig_builder: "true"
      orc8r.io/metrics_exporter: "true"
      orc8r.io/obsidian_handlers: "true"
      orc8r.io/state_indexer: "true"
      orc8r.io/stream_provider: "true"
    annotations:
      orc8r.io/state_indexer_types: "directory_record"
      orc8r.io/state_indexer_version: "1"
      orc8r.io/stream_provider_streams: "configs"
      orc8r.io/obsidian_handlers_path_prefixes: >
        /,
        /magma/v1/channels,
        /magma/v1/events,
        /magma/v1/networks,
        /magma/v1/networks/:network_id,

  streamer:
    host: "localhost"
    port: 9082
    proxy_type: "clientcert"

  metricsd:
    host: "localhost"
    port: 9084
    echo_port: 10084
    proxy_type: "clientcert"
    labels:
      orc8r.io/obsidian_handlers: "true"
    annotations:
      orc8r.io/obsidian_handlers_path_prefixes: >
        /magma/v1/networks/:network_id/alerts,
        /magma/v1/networks/:network_id/metrics,
        /magma/v1/networks/:network_id/prometheus,
        /magma/v1/tenants/:tenant_id/metrics,
        /magma/v1/tenants/targets_metadata,

  certifier:
    host: "localhost"
    port: 9086
    proxy_type: "internal"

  bootstrapper:
    host: "localhost"
    port: 9088
    proxy_type: "open"

  accessd:
    host: "localhost"
    port: 9091
    proxy_type: "clientcert"

  obsidian:
    host: "localhost"
    port: 9093
    proxy_type: "obsidian"

  dispatcher:
    host: "localhost"
    port: 9096
    proxy_type: "clientcert"

  directoryd:
    host: "localhost"
    port: 9100
    proxy_type: "clientcert"

  state:
    host: "localhost"
    port: 9105
    proxy_type: "clientcert"

  device:
    host: "localhost"
    port: 9106
    proxy_type: "clientcert"

  configurator:
    host: "localhost"
    port: 9108
    proxy_type: "clientcert"

  tenants:
    host: "localhost"
    port: 9110
    echo_port: 10110
    proxy_type: "clientcert"
    labels:
      orc8r.io/obsidian_handlers: "true"
    annotations:
      orc8r.io/obsidian_handlers_path_prefixes: >
        /magma/v1/tenants,
        /magma/v1/tenants/:tenants_id,

  service_registry:
    host: "localhost"
    port: 9180
    proxy_type: "clientcert"
```

**Comment by jpad-freedomfi** [comment]
I see your output has established connections to configurator and certifier that my output does not have. (port 9086 and 9108)
The contents of my /etc/magma/configs/orc8r/certifier.yml and configuration.yml are just the license boiler plate. no real configuration params. is that correct?

**Comment by jpad-freedomfi** [comment]
Also, I see nothing in my /var/opt/magma/configs/orc8r about smsd. 

is there a document that shares what configuration steps are necessary for smsd? 

Is anything special needed in config directories besides based orc8r install?

**Comment by sourabh-nanoti** [comment]
Hey @jpad-freedomfi ,
Can you provide logs for both the nginx pods ? They are named something like - orc8r-nginx-5dcf6d5cbc-dpszw

**Comment by jpad-freedomfi** [comment]
@sourabh-nanoti 
[nginx_logs_1.txt](https://github.com/magma/magma/files/5812214/nginx_logs_1.txt)
[nginx_logs_2.txt](https://github.com/magma/magma/files/5812215/nginx_logs_2.txt)

**Comment by sourabh-nanoti** [comment]
So this is a clear error that is happening at nginx -
{"nginx.time_local": "13/Jan/2021:22:46:45 +0000","nginx.remote_addr": "10.10.101.164","nginx.request": "POST /magma.lte.SmsD/GetMessages HTTP/2.0","nginx.request_method": "POST","nginx.request_uri": "/magma.lte.SmsD/GetMessages","nginx.status": 499,"nginx.body_bytes_sent": 0,"nginx.request_length": 39,"nginx.request_time": 14.610,"nginx.server_name": "~^(?<srv>.+)-controller.lab.freedomfi.com$","nginx.clientcert_port": 9120,"nginx.open_port": 9070,"nginx.client_serial": "29DBAF49DA3813196328D0B398E2C585","nginx.client_cn": "7bf97027-6442-4641-9736-4caf544f4ed7"}
2021/01/13 22:46:45 [info] 9#9: *3106004 client terminated stream 9 due to internal error while connecting to upstream, client: 10.10.101.164, server: ~^(?<srv>.+)-controller.lab.freedomfi.com$, request: "POST /magma.lte.SmsD/GetMessages HTTP/2.0", upstream: "grpc://172.20.95.223:9120", host: "smsd-controller.lab.freedomfi.com"

**Comment by mpgermano** [comment]
@jpad-freedomfi The lack of connections to configurator or certifier indicates that the request is never making it to the identity check middleware which is used to parse gwID and nwID from all gateway calls. My current suspicion is that somehow port 9120 (smsd port) is not exposed on the orc8r controller pod.

You can check this by running: 
`kubectl -n orc8r describe pod orc8r-controller-xxxxx-yyyy` 

You should see port 9120 listed under the "Ports" section.

**Comment by jpad-freedomfi** [comment]
you are correct. 9120 is not there. Is this output somehow private? Or can I post the whole thing?

Either way, 9120 is not there, my ports list ends at 9108/tcp

**Comment by jpad-freedomfi** [comment]
I'm not an orc8r expert. How/where is that configured to be added to the list?

**Comment by mpgermano** [comment]
I see that the orc8r was deployed on AWS so my assumption is that terraform was used for the install. Please let me know if this is not case. 

With terraform, the templated values file used for the deployment (`magma/orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl`) should already have the variable hardcoded: 

```
controller:
  ...
  service:
    portEnd: 9121
```
Let's first double check that this is the case.

**Comment by jpad-freedomfi** [comment]
@mpgermano yes to AWS and terraform. Where would I be looking for that path/file?

**Comment by mpgermano** [comment]
The path to check this exists wherever the terraform directory that has been used to deploy the orc8r. In that directory we can check the template file that was used to deploy at `<tf_directory>/.terraform/modules/orc8r-app/orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl`

**Comment by 119Vik** [comment]
@mpgermano  just checked latest https://github.com/magma/magma/blob/master/orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl and mentioned lines are not there
it seems to be moved to https://github.com/magma/magma/blob/master/orc8r/cloud/helm/orc8r/README.md
where we can see :
controller.service.portEnd | Controller service inclusive port range end. | 9108

Let Us update our deployment with new value  controller.service.portEnd=9121

**Comment by 119Vik** [comment]
Line was added here: https://github.com/magma/magma/commit/e70f41fc60af6e18f87dee5128946d0aee48e1fe#diff-327b5da26ddc1a8165cd53c15d196e5f25f35febf0e6e6ac1b4c30f811a14d6e 
and then delete here: https://github.com/magma/magma/commit/00627f7373935ea92a940a22721b532059813d99#diff-327b5da26ddc1a8165cd53c15d196e5f25f35febf0e6e6ac1b4c30f811a14d6e

**Comment by mpgermano** [comment]
We have changed our deployment for version 1.4 removing the need for this variable. This is the reason why it is no longer on master. The readme on master needs to be updated to remove that parameter. For v1.3 though, `portStart` still exists and is set properly.

**Comment by 119Vik** [comment]
Also I see that https://magma.github.io/magma/docs/orc8r/deploy_install page was updated - and now it says 
```
Make sure that the source variables for the module definitions point to github.com/magma/magma//orc8r/cloud/deploy/terraform/<module>?ref=v1.3. Adjust any other parameters as you see fit - check the READMEs for the relevant Terraform modules to see additional variables that can be set.

The ?ref=v1.3 argument is very important to include in the Terraform source parameters for your modules - we will be making large sweeping changes to these modules on the master branch of Magma in the near future.
```
At the moment when we deployed our env it was `?ref=v1.2` . Current `?ref=v1.3` has correct `portEnd` value

**Comment by sourabh-nanoti** [comment]
Hey @119Vik & @jpad-freedomfi , can you confirm if updating the env to 1.3 resolves the issue? Thanks.

**Comment by ulaskozat** [comment]
I am closing this issue. Let's open a new issue for config related issues if there is anything new.
