### ISSUE TITLE
NMS Blank Screen trying to fetch eNB Status

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#3765]
### Your Environment

- **Version:** 1.3 (commit de7c8e314fc2388da17f327adae838a919fda2e9 (HEAD -> v1.3, origin/v1.3))
- **Affected Component:** Orchestrator and NMS
- **Affected Subcomponent:** 
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

We have attempted to upgrade a 1.3 stable deployment to the head of 1.3. In doing so we have problem with NMS where it hangs/blank screens when trying to navigate to view eNB status. 

When we delete all eNBs from all networks, NMS is ok. When adding eNB, we received "service unavailable" we were able to get past this error, but now see when NMS goes to fetch eNB status another hang occurs. 

Also seems data is not getting passed to AGW as S1AP setup returns PLMN unknown and failure for configured eNB. 

**To Reproduce**
1. Upgrade NMS and AGW from v1.3 stable to commit mentioned above. 
2. Ensure network(s) have eNBs configured at the time of upgrade. 
3. Log in to NMS
4. Navigate to equipment/overview/enodeb
5. see NMS blank screen and console errors (HAR file attached)
[freedomfi.nms.lab.freedomfi.com.har.zip](https://github.com/magma/magma/files/5562070/freedomfi.nms.lab.freedomfi.com.har.zip)

**Expected behavior**
NMS should be able to create and get eNodeB elements. If upgrade introduces new migration steps these should be called out in release notes. 

We believe "create" was broken by this commit. This applies to both API and NMS. 
https://github.com/magma/magma/commit/047edcdf5cb377ce86068c9fd68b1d5d19fc1b7a 

We have not found the source of error for "get" of eNB element.

**Comment by jpad-freedomfi** [comment]
@joary Here is what I can share. We'll have more tomorrow. But if anyone needs anything today please tag me. I can try and help.

**Comment by karthiksubraveti** [comment]
@jpad-freedomfi can you attach a screen recording of the issue you are seeing, will help is to understand this better.

**Comment by jpad-freedomfi** [comment]
https://drive.google.com/file/d/1-Mbu3Iz9mgKAz6BMseAkk7HBTIAn8AW_/view?usp=sharing 

please enjoy an audio education about continents while watching courtesy of my 5 yr old 🤣
@karthiksubraveti

**Comment by ardzoht** [comment]
Hi @jpad-freedomfi thanks for flagging this, I'm interested on seeing what's the eNodeb config for this, if you have access to the API, could you share what's the config for the eNodeb under the `test_federated_lte` network?

Update: Just synced up with @karthiksubraveti, we're seeing that on eNB creation on NMS there's a partial failure on API, there's a fix for this that's merged that should take care of this https://github.com/magma/magma/pull/3699

**Comment by karthiksubraveti** [comment]
@jpad-freedomfi this might probably fixed with this PR https://github.com/magma/magma/pull/3699. Can you try backporting this and attempting to run this again ? Prior to that delete those enodeBs. Looks like we end up with some bad state when eNodeBs addition fails with "service unavailable" message

**Comment by jpad-freedomfi** [comment]
So far I am unable to backport things myself. @berezovskyi-oleksandr can you halp plez? try the 3699 deal and see how it goes?

**Comment by jpad-freedomfi** [comment]
and yes @ardzoht we did orc8r upgrade to same version.

**Comment by berezovskyi-oleksandr** [comment]
@jpad-freedomfi , I've cherry-picked commit cb238d337eb4ca5db56c0434b50ba7cb649bc349 and re-built/re-deployed orc8r and NMS. 

Now it is possible to add eNb via NMS and the configuration is correct, but eNb still can't establish a connection to the mme with "unknown-PLMN" error. After that, all eNb configuration at NMS is gone:
```
{
  "attached_gateway_id": "nuc",
  "config": {
    "cell_id": 0,
    "device_class": "Baicells Nova-233 G2 OD FDD",
    "transmit_enabled": false
  },
  "description": "ACC170317000127",
  "enodeb_config": {
    "config_type": "MANAGED",
    "managed_config": {
      "cell_id": 0,
      "device_class": "Baicells Nova-233 G2 OD FDD",
      "transmit_enabled": false
    }
  },
  "name": "ACC170317000127",
  "serial": "ACC170317000127"
}
```

I've set manually (there is no possibility in the NMS for now) the eNb to unmanaged mode with the configuration:
```
{
  "attached_gateway_id": "nuc",
  "config": null,
  "description": "ACC170317000127",
  "enodeb_config": {
    "config_type": "UNMANAGED",
    "unmanaged_config": {
      "cell_id": 0,
      "ip_address": "10.0.2.239",
      "tac": 2
    }
  },
  "name": "ACC170317000127",
  "serial": "ACC170317000127"
}
```

This brokes NMS (`config` section is empty and it became empty even in case of PUT of some data there), but eNb now can connect to the mme.

**Comment by berezovskyi-oleksandr** [comment]
Wanted to notice, that before I cherry-picked that commit, I've took a look at the creation process and found, that `lte` service crashes at the orc8r with the traceback:
```
echo: http: panic serving 127.0.0.1:42500: runtime error: invalid memory address or nil pointer dereference
goroutine 29 [running]:
net/http.(*conn).serve.func1(0xc000158640)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x11b5ee0, 0x1c29fe0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
magma/lte/cloud/go/services/lte/obsidian/models.(*EnodebConfig).validateEnodebConfig(0x0, 0x1444640, 0xc00015b560)
	/src/magma/lte/cloud/go/services/lte/obsidian/models/validate.go:349 +0x26
magma/lte/cloud/go/services/lte/obsidian/models.(*Enodeb).ValidateModel(0xc0000ca690, 0x1260500, 0xc0000ca690)
	/src/magma/lte/cloud/go/services/lte/obsidian/models/validate.go:332 +0x68
magma/lte/cloud/go/services/lte/obsidian/handlers.createEnodeb(0x1454de0, 0xc000182000, 0xc0001669a0, 0xc0000b80a3)
	/src/magma/lte/cloud/go/services/lte/obsidian/handlers/handlers.go:314 +0xe4
github.com/labstack/echo.(*Echo).Add.func1(0x1454de0, 0xc000182000, 0x4, 0xc0000b8095)
	/root/go/pkg/mod/github.com/labstack/echo@v0.0.0-20181123063414-c54d9e8eed6c/echo.go:488 +0x8a
github.com/labstack/echo.(*Echo).ServeHTTP(0xc00000c1e0, 0x143c5e0, 0xc00024a0e0, 0xc000256300)
	/root/go/pkg/mod/github.com/labstack/echo@v0.0.0-20181123063414-c54d9e8eed6c/echo.go:591 +0x222
net/http.serverHandler.ServeHTTP(0xc0001220e0, 0x143c5e0, 0xc00024a0e0, 0xc000256300)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000158640, 0x143e5a0, 0xc00029c080)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

I found, that there is no check at [the EnodebConfig validation code](https://github.com/magma/magma/blob/v1.3/lte/cloud/go/services/lte/obsidian/models/validate.go#L332-L334). Changing code onto:
```
	if m.EnodebConfig != nil{
		if err := m.EnodebConfig.validateEnodebConfig(); err != nil {
			return err
		}
	}
```
fixed creation process.

**Comment by karthiksubraveti** [comment]
Yes. I opened the following issue for that https://github.com/magma/magma/issues/3675. If you have a fix already for this please push that upstream. @ardzoht did we already fix this issue ?

**Comment by berezovskyi-oleksandr** [comment]
@karthiksubraveti , I've created PR with the fix - https://github.com/magma/magma/pull/3786 . We need to have this backported to v1.3 branch.

**Comment by ardzoht** [comment]
@berezovskyi-oleksandr Merged the PR, we'll backport this to the v1.3 branch

**Comment by karthiksubraveti** [comment]
Looks like all fixes have merged. Will close this issue
