### ISSUE TITLE
Fix sync RPC connection disruptions on dispatcher

### ISSUE THREAD

**Issue by mpgermano** [magma/magma#4833]
Sync RPC has historically caused issues with federated deployments. Here we intend to root cause and fix this issue. 

The issue appears most frequently when load testing a federated deployment. Above 1k attaches (producing s6a and session proxy RPC calls), the underlying h2 connection gets closed. This causes all calls through feg relay to fail until magmad on the feg can initiate a new sync RPC connection. It is worth noting that orc8r's shift from nghttpx to nginx as made the issue worse.

**Comment by 119Vik** [comment]
@mpgermano  I think we faced this issue with one of our deployments so I'm trying to investigate it
Few questions I have so far
It seems that this line https://github.com/magma/magma/blob/cbd159bdfc94cf880e8f15dad5489fa5c637ffbd/orc8r/gateway/python/magma/magmad/sync_rpc_client.py#L158 will hide all the errors which happen in the scope of proxy_client isn't it? 
Also, it seems that we don't care here if the message was delivered or not...
https://github.com/magma/magma/blob/cbd159bdfc94cf880e8f15dad5489fa5c637ffbd/orc8r/gateway/python/magma/magmad/proxy_client.py#L101

Here we are trying to create new client for each new message https://github.com/magma/magma/blob/cbd159bdfc94cf880e8f15dad5489fa5c637ffbd/orc8r/gateway/python/magma/magmad/proxy_client.py#L54

I wonder if we call this https://github.com/magma/magma/blob/cbd159bdfc94cf880e8f15dad5489fa5c637ffbd/orc8r/gateway/python/magma/magmad/proxy_client.py#L122 function 1billion times how many sockets/ports will be allocated?  I see no Singleton in H2 implementation so I assume that in case of intensive usage this code may run out of some resource?

**Comment by ulaskozat** [comment]
@mpgermano and @ardzoht are we currently investigating this issue actively or is it in backlog?

**Comment by ulaskozat** [comment]
@119Vik are you willing to contribute to resolve this issue in tech debt week?

**Comment by 119Vik** [comment]
@ulaskozat yeah, at least I'm happy to help with debugging, which we are going to start tomorrow. As a result of debugging, I'd be happy to help with a fix if it's in my area of competence.

**Comment by 119Vik** [comment]
@ulaskozat 
here's what i found in kernel.log for magmaD when we are losing s6a functionality
following message appears for several hours. docker restart of the container is not able to fix it.
 ```
1595368:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: ERROR:asyncio:Exception in callback _SelectorSocketTransport._read_ready()
1595369:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: handle: <Handle _SelectorSocketTransport._read_ready()>
1595370:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: Traceback (most recent call last):
1595371:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:   File "/usr/local/lib/python3.5/dist-packages/h2/connection.py", line 224, in process_input
1595372:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:     func, target_state = self._transitions[(self.state, input_)]
1595373:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.RECV_PING: 14>)
1595374:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: 
1595375:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: During handling of the above exception, another exception occurred:
1595376:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: 
1595377:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: Traceback (most recent call last):
1595378:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:   File "/usr/lib/python3.5/asyncio/events.py", line 127, in _run
1595379:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:     self._callback(*self._args)
1595380:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 730, in _read_ready
1595381:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:     self._protocol.data_received(data)
1595382:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:   File "/usr/local/lib/python3.5/dist-packages/aioh2/protocol.py", line 256, in data_received
1595383:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:     events_ = self._conn.receive_data(data)
1595384:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:   File "/usr/local/lib/python3.5/dist-packages/h2/connection.py", line 1463, in receive_data
1595385:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:     events.extend(self._receive_frame(frame))
1595386:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:   File "/usr/local/lib/python3.5/dist-packages/h2/connection.py", line 1486, in _receive_frame
1595387:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:     frames, events = self._frame_dispatch_table[frame.__class__](frame)
1595388:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:   File "/usr/local/lib/python3.5/dist-packages/h2/connection.py", line 1761, in _receive_ping_frame
1595389:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:     ConnectionInputs.RECV_PING
1595390:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:   File "/usr/local/lib/python3.5/dist-packages/h2/connection.py", line 229, in process_input
1595391:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]:     "Invalid input %s in state %s" % (input_, old_state)
1595392:Jun 22 15:34:20 ip-10-10-2-239 4c1da1104c9b[1226]: h2.exceptions.ProtocolError: Invalid input ConnectionInputs.RECV_PING in state ConnectionState.CLOSED
```


In the same time from Orc8r feg_relay pod we have following error:
```
E0622 16:37:15.764889       1 handler.go:116] [ERROR /magma.feg.S6aProxy/AuthenticationInformation]: rpc error: code = Internal desc = err sending request gwId:"......" authority:"s6a_proxy" path:"/magma.feg.S6aProxy/AuthenticationInformation" headers:<key:"Content-Type" value:"application/grpc" > headers:<key:"Grpc-Timeout" value:"59999969u" > headers:<key:"Te" value:"trailers" > headers:<key:"User-Agent" value:"grpc-go/1.31.0" > payload:"........."  to gateway: Queue does not exist for gwId .......
```

**Comment by ulaskozat** [comment]
@119Vik we need a new owner for this issue. Tentatively I included @ardzoht and @uri200 as owners. We should have a sync up meeting on this as I am not sure if the nature of the problem has changed over time.

**Comment by ekowtaylor** [comment]
@wallyrb to validate scope and priority with partner

**Comment by ekowtaylor** [comment]
@ardzoht , @talkhasib we were able to confirm with FFi that this is perhaps the most important issue that needs a shorter term resolution cc: @wallyrb

**Comment by ardzoht** [comment]
thanks for the quick confirmation Ekow, cc @ulaskozat

**Comment by ulaskozat** [comment]
@ekowtaylor @ardzoht @talkhasib then let's prioritize this. @ardzoht do you have any guestimate on how long would this take to close?

**Comment by ardzoht** [comment]
This should take a good part of the sprint (I expect minimum 2 weeks) since it involves root causing the instability on the socket between the proxy on the AGW and the nginx server on the Orc8r and the FeG s6a proxy.

I'm checking with @sudhikan to see if we can get a federated deployment (maybe on Spirent) that we can use to induce the load

**Comment by ulaskozat** [comment]
@119Vik what kind of debugging, troubleshooting support can you provide on this issue?

**Comment by electronjoe** [comment]
Perhaps we can begin by verifying the leaking FD hypothesis, which seems quite possible given @119Vik's reports.  I've filed https://github.com/magma/magma/issues/8173 to advocate that we expose FD resource count per magma binary - which is a common resource monitoring telemetry which Magma seems to not yet have.

@119Vik are you able to validate the number of open FD count per Magma binary for an AGW under heavy load, perhaps over time - to see if we are indeed leaking resources here?  This can be done from the Linux proc enviornment manually by exploring `/proc/PID/fd` within which each file is an open file descriptor (file or network). Or by use of `lsof -p <pid_of_magma_daemon>`. What do you see?

**Comment by electronjoe** [comment]
In reviewing the pointers by @119Vik from March 26th, I'm also trying to trace our use of timeouts by the https://github.com/magma/magma/blob/cbd159bdfc94cf880e8f15dad5489fa5c637ffbd/orc8r/gateway/python/magma/magmad/sync_rpc_client.py#L158 implementation - and so far am not spotting them (or they are at least not obvious). I want to audit that this call is not unbounded in potential execution duration (and would therefore pile up under some failure modes).

[Edit: if this was Golang, we would be passing contexts around with deadlines so that expectations of maximum runtime duration were clear at the calling functions - we seem to lack this in this Python implementation]

**Comment by 119Vik** [comment]
> @119Vik what kind of debugging, troubleshooting support can you provide on this issue?

we have env where it's observed and it's more or less clear how to reproduce it so we are happy to setup one more debugging session

**Comment by 119Vik** [comment]
> Perhaps we can begin by verifying the leaking FD hypothesis, which seems quite possible given @119Vik's reports. I've filed #8173 to advocate that we expose FD resource count per magma binary - which is a common resource monitoring telemetry which Magma seems to not yet have.
> 
> @119Vik are you able to validate the number of open FD count per Magma binary for an AGW under heavy load, perhaps over time - to see if we are indeed leaking resources here? This can be done from the Linux proc enviornment manually by exploring `/proc/PID/fd` within which each file is an open file descriptor (file or network). Or by use of `lsof -p <pid_of_magma_daemon>`. What do you see?

I didn't so far - starting monitoring this

**Comment by 119Vik** [comment]
@electronjoe quick check sofar
9 connected users lead to the following steady load (numbers are # of FDs).
```
#                   open     stuck     max         
fs.file-nr = 1664       0       198633
MagmaD: 25
S6A: 7
SessionProxy: 11
```
Number are floating a bit +/- 1 
CPU - 2-15% for both vCores RAM is 500Mbs of 2GBs as per htop
trying to connect 1 UE leads to +1 FD jump approximately

**Comment by uri200** [comment]
@119Vik what is the version of Magma. you are seeing this 

@ulaskozat @ardzoht I remember I was able to generate issues with syncRPC easily in our AGW at teravm in the the past just running a command that sends multiple AIR authentications to the FEG

``
magma@ubuntuAGW:~/uri$ ./s6a_cli air -remote_s6a -range 400 -rate 10 999991234567810
``

However, I am not able to see any issue under master anymore.

I can run test of 5k UE with a rate of 50 UEs and AGW+FEG will not miss a request

**Comment by electronjoe** [comment]
> @119Vik what is the version of Magma. you are seeing this

I had a slack message from @119Vik this morning:

```
This issue was replicated when all AGW - Orc8r - FEG were at 1.3.*
recently we updated Orc8r to 1.5 so now we are testing several configs
AGW 1.3              FEG 1.3
       \  A         /B
          Orc8r 1.5
        / C         \D
AGW 1.5.            FEG 1.5 
```

Are you seeing this issue still with the version topology here, @119Vik ?

**Comment by electronjoe** [comment]
@119Vik You indicated in slack chat that a fix for this bug when it occurs is to `restart FEG` - can you confirm here? This would indicate that at least the state / behavior of FEG is in the mix.

@uri200 pending version information from @119Vik, would we be able to attempt repro via teravm?

**Comment by uri200** [comment]
Hi @electronjoe I tried to use the same procedure I did in the past to trigger issues on teravm (magma 1.7) and I was not able to trigger them.  The test is very simple to do so we can try it if you find out something.

However, if this is for an older version, unfortunately teravm uses staging orc8r which is at 1.7 already. 

Ibutbif the issue is already fixed on newer versions, I think it would be better to upgrade magma to 1.6 on that specific setup that is failing.

**Comment by 119Vik** [comment]
@electronjoe can't confirm so far that issues is replicated with 1.5 cause we have issues with security_mode for UEs so can't generated some real load.

**Comment by 119Vik** [comment]
@uri200 we started testing  1.6 already so we will check same issue with 1.6 soon

**Comment by 119Vik** [comment]
@uri200  we started testing 1.6 as well so we will check it there soon

**Comment by jpad-freedomfi** [comment]
@electronjoe and @uri200  update here. FeG still angry, doing funny spamming of CCR messages to OCS without subscription IDs. See pcap attached. 
[feg_spamming_OCS.pcapng.zip](https://github.com/magma/magma/files/7003461/feg_spamming_OCS.pcapng.zip)

 Also, MAC failure issue still exists, just update https://github.com/magma/magma/discussions/8060 

Hard to debug these when both issues persist. Customer wants to stay on 1.3.2 where FeG restart interval is ~24hrs. In current state customer has to restart more like every 4-8 hrs. 

We can setup debug session with the system if that helpful.

**Comment by electronjoe** [comment]
@jpad-freedomfi Thanks for the update! I have reached out on slack to a group of us, asking to set up a debug session.

**Comment by electronjoe** [comment]
@uri200 pointed out in slack that we only support uniform version deploys (AGW, FEG, Orc8r, NMS at same major release version).  Per [comment](https://github.com/magma/magma/issues/4833#issuecomment-885655638) above it appears this is a mixed deployment, so @uri200 is asking @119Vik to clarify if that is true, and test a uniform Magma 1.6 deploy.

**Comment by electronjoe** [comment]
> @electronjoe and @uri200 update here. FeG still angry, doing funny spamming of CCR messages to OCS without subscription IDs. See pcap attached.

@uri200 thinks these PCAP do not necessarily point to any Sync RPC related issues, from the logs present.  Instead he worries about general Diameter behavior here (perhaps separate from this GH Issue).

**Comment by uri200** [comment]
Hey @jpad-freedomfi, thanks for reporting. 

As mentioned on our slack conversation, that spamming issue is at diameter interface. This can be caused by multiple factors. Syncrpc issues will be observed mainly on magmad and feg_relay on or8cr (as missing responses back). But here it looks like we get all the responses (?)

Can you please  provide logs from magmad on AGW and FEG  and feg_relay on orc8r to see if there are errors there?
Can also tell us what exactly is this test doing so we can better understand the PCAP?

Also note in pcap I am seeing `user unknown` as a response to some users included on CCR-I. So maybe those subscribers are missing on OCS 

Finally, maybe is worth trying changing the default initial grant sessiond requests. By default this is set to `default_requested_units: 200000` at `sessiond.yml` file on AGW. Maybe this value is too low and it is causing sessiond to request too many updates. Try setting it to 2Mb (2000000) or 20Mb (20000000) 


![image](https://user-images.githubusercontent.com/16157139/129918113-4adadfd4-3dd8-4824-b370-5d30980d707e.png)

**Comment by uri200** [comment]
btw, I created this https://github.com/magma/magma/issues/8670 which may help to reduce that spamming

**Comment by jpad-freedomfi** [comment]
> @uri200 pointed out in slack that we only support uniform version deploys (AGW, FEG, Orc8r, NMS at same major release version). Per [comment](https://github.com/magma/magma/issues/4833#issuecomment-885655638) above it appears this is a mixed deployment, so @uri200 is asking @119Vik to clarify if that is true, and test a uniform Magma 1.6 deploy.

Current environment is v1.5 for all. AGW, orc8r, FeG. That is what latest logs have been produced from.

**Comment by electronjoe** [comment]
OK. Correct me if I'm wrong but I believe where we have left this now in slack is as follows:
- Waiting for evidence of Sync RPC bug on a deployment that is {AGW, FEG, Orc8r} at 1.6 release

**Comment by jpad-freedomfi** [comment]
@electronjoe 
correction, 1.5 release. 
Waiting for evidence of Sync RPC bug on a deployment that is {AGW, FEG, Orc8r} at 1.5 release

**Comment by electronjoe** [comment]
@jpad-freedomfi We'll close this GH Issue until FFi sees evidence of Sync RPC bug on a deployment that is {AGW, FEG, Orc8r} at 1.5 release.

Please re-open / post updates if and when that happens! Thank you for your help.
